name: Changesets
on:
  push:
    branches:
      - main

env:
  CI: true
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    name: static checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Update npm
        run: pnpm install -g npm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: create and publish versions
        id: changesets
        continue-on-error: true
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GRADIO_PAT }}
      - name: publish to pypi
        uses: "pngwn/gradio-actions/actions/publish-pypi@main"
        with:
          use-oidc: true
