name: Changesets
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled, closed]
    branches:
      - main
  issue_comment:
    types: [edited]

env:
  CI: true
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  publish:
    permissions: write-all
    name: static checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.number || github.event.issue.number }}
      - name: generate changeset
        uses: "./.github/actions/generate-changeset"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
